# >     ___         __             _          ______                __
# >    /   |  _  __/ /_____  ____ ( )_____   / ____/___ ___  ____  / /____  _____
# >   / /| | | |/_/ __/ __ \/ __ \|// ___/  / __/ / __ `__ \/ __ \/ __/ _ \/ ___/
# >  / ___ |_>  </ /_/ /_/ / / / / (__  )  / /___/ / / / / / /_/ / /_/  __(__  )
# > /_/  |_/_/|_|\__/\____/_/ /_/ /____/  /_____/_/ /_/ /_/\____/\__/\___/____/
# >
# >> Axton's Emotes | Configuration
# For more information, visit: https://emotes.axtonprice.xyz/

# >> Language
# Sets the language used for in-game plugin messages.
# For a full list of available languages, please refer to https://emotes.axtonprice.xyz/languages/
language: en

# >> Self-Executions
# Allows players to execute emote commands on themselves.
# Default: false
allow-self-executions: false

# >> List Commands
# Enables the /emotes and /expressions commands to view permitted emotes. When enabled, anyone can list commands.
# When disabled, only server operators or players with the 'axtonsemotes.admin.list-override' permission can list commands.
# Default: true
allow-list-commands: true

# >> Shared Emotes Toggle
# Allows players to use /toggleemotes, removing the ability for others to execute shared emotes on them.
# If both below are enabled, the player must have the 'axtonsemotes.emotes.selftoggle' permission to run the toggle command.
allow-self-toggle:
  enabled: true # true
  require-permission: false # false

# >> Shared Emote Radius
# Sets the minimum distance (in blocks) required between the sender and target player to execute shared emotes.
# Players with axtonsemotes.admin.bypassradius permission can bypass the configured radius limit below.
emote-radius:
  enabled: true # true
  distance: 15 # 15

# >> Emote Cooldown
# Sets a cooldown period (in seconds) between emote executions per player.
# Players with axtonsemotes.admin.bypasscooldown permission can bypass the configured cooldown below.
emote-cooldown:
  enabled: true # true
  duration-seconds: 3 # 3

# >> Default Effects
# Specifies the default particle and sound effects if the specified enum constant is invalid (NOT if the effect is set to 'none').
# Defaults: CRIT, ENTITY_ITEM_PICKUP
default-effects:
  particle: "CRIT"
  sound: "ENTITY_ITEM_PICKUP"

# >> Debug Mode
# Configure debug mode, which logs detailed information about command executions. This is useful
# for troubleshooting but will result in many console messages.
debug-mode:
  enabled: false # false
  log-to-file: true # true
  file-name: "debug.log" # debug.log

# >> Plugin Versioning & Updates
# Configure update checks and notifications:
updates:
  # Automatically checks for plugin updates every 12 hours and on server startup.
  # Default: true
  check-for-latest: true

  # Notifies operators and players with the axtonsemotes.admin.updatenotify permission when a newer version is available.
  # Default: true
  notify-players-on-update: true

# >> Metrics Tracking
# Enables BStats anonymous metrics tracking. Learn more at https://bstats.org/
# Default: true
enable-metrics: true

# The current version of the plugin.
# >> Do NOT modify this! <<
config-version: 1.5.2